### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lumost** [jelmerk/hnswlib#1]
Great Library!  can you please add a License to this project, hopefully MIT or similar :)

thanks!

**Comment by jelmerk** [comment]
Hi, Currently it's still very much a work in progress. I'll think about peripheral matters once its in a stable state

**Comment by UlfbertHuynh** [comment]
Hi jelmerk, I'm very impressed with your work and want to use some portion of your code for a project in academia. Can I know the license as well as the way to give credit?

**Comment by ashfaq92** [comment]
Hi @jelmerk, personally I think pretty much of work of core HNSW is done already in this package. Now you can enhance it to spark or other frameworks. It is up to you. But most of others (like me) needed java implementation of core-HNSW which is perfectly provided by your package.
So please let us know about license so that we may freely contribute to the project and use it in our works by giving you credit the way you chose.
Thanks!

**Comment by ashfaq92** [comment]
![license](https://user-images.githubusercontent.com/28701122/71777232-09ad1180-2fd8-11ea-8fb1-5bdd11e491de.PNG)
Hi @jelmerk! in your pom.xml file, you included apache license. Does this covers license of whole project file? Please update license conditions because i have used it in acedemia and just waiting for your reply

**Comment by lfcnassif** [comment]
Adding a license is important, so users could know if they can use the library in their projects and give credit. I would like to test and use just the core library in a java project GPL licensed with some linking exceptions...

**Comment by ashfaq92** [comment]
Big thanks for providing [hnsw maven](https://mvnrepository.com/artifact/com.github.jelmerk) dependencies with apache license. But there is no documentation exists how to use them. Please, update your code examples by using maven dependencies. 
Thanks.

**Comment by jelmerk** [comment]
Added license file at https://github.com/jelmerk/hnswlib/blob/master/LICENSE.txt

**Comment by lfcnassif** [comment]
Wonderful, thank you and congratulations for this great library!
