### ISSUE TITLE
Can it support jdk1.7？Android 5.1 does not support 1.8。

### ISSUE THREAD

**Issue by KeiAn** [jelmerk/hnswlib#18]
Can it support jdk1.7？Android 5.1 does not support 1.8。

**Comment by jelmerk** [comment]
The short answer is no.

Long answer is, it uses things like Optionals, default methods and lambda's etc that are all unsupported on java 7. So it cannot simply be compiled to run on jdk 1.7 without making alterations to the code / making the code less nice

Plus both jdk7 and lollypop have been unsupported for some years now so

You can always fork the project i suppose, it should not be a lot of work to get it to compile on jdk7

**Comment by ashfaq92** [comment]
> fork the project i suppose

We can not even fork the code that has no [license](https://choosealicense.com/no-permission/). Meanwhile, other implementations that are based on your code include GPL licence [Scalable HNSW](https://github.com/UlfbertHuynh/scalable-hnsw) So why not you include license so that we fork it and implement it according to our need?
