### ISSUE TITLE
hnswlib-spark slow on the retrieval of millions items

### ISSUE THREAD

**Issue by wangruinju** [jelmerk/hnswlib#27]
In our use case, we have 20M ~ 100M items with 100d embedding for query top_k (20 ~ 1000). I am seeking any suggestion for speeding up the spark job.

one example used in our case,
```scala
val hnsw = new HnswSimilarity()
        .setIdentifierCol("id")
        .setQueryIdentifierCol("id")
        .setFeaturesCol("normalizedFeatures")
        .setNumPartitions(10)
        .setM(16)
        .setEf(200)
        .setEfConstruction(200)
        .setK(20)
        .setDistanceFunction("inner-product")
        .setSimilarityThreshold(0.3)
        .setPredictionCol("approximate")
        .setExcludeSelf(true)
```

Thanks a lot!

**Comment by jelmerk** [comment]
It's hard to say without knowing your setup. 

But some general tips

1. Use the suggested configuration from the readme (make sure speculation and dynamic allocation are off etc)
2. use inner product with a normalizer instead of cosine distance 
3. increasing the number of partitions will speed up indexing at the expense of slowing down querying 
4. increasing the number of replicas (setNumReplicas) will speed up querying  at the expense of resource usage, you use if  you set it to one, you will need to double the number of executors you use when querying

A good way to work out why things are slow is to look at the logs and look for lines that contain the word partition

**Comment by wangruinju** [comment]
Thanks for the tips!
