### ISSUE TITLE
Why is there no float-64 support in hnswlib-core-jdk17

### ISSUE THREAD

**Issue by chenjia123** [jelmerk/hnswlib#49]
As the title says.

**Comment by jelmerk** [comment]
No real reason other than that it's work and I haven't gotten around to it. Feel free to contribute it. 

Unfortunately due to what I think is a bug in the jdk it does not seem to be possible to create a generic implementation that works for all species. So you  basically have to do the same thing over and over again.

I filed a bug for it but I don't think it's been addressed
